name: IO
version: "4.9.2"
license: "GPL-3.0-or-later"
date: 2025-06-20
description: |
    Bindings for low level C library I/O routines

authors:
    - name: Max Neunhöffer
      url: mailto:max@9hoeffer.de

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.12"

www: https://gap-packages.github.io/io
readme: README.md
packageinfo: https://gap-packages.github.io/io/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/io/releases/download/v4.9.2/io-4.9.2.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/io/releases/download/v4.9.2/io-4.9.2.tar.bz2

abstract: |
    The <span class="pkgname">IO</span> package, as its name suggests,    provides bindings for <span class="pkgname">GAP</span> to the lower    levels of Input/Output functionality in the C library.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    input, output, I/O, C-library, network, http, object serialisation, unpredictable random numbers, TCP/IP, inter process communication, background jobs, parallel skeletons, I/O multiplexing.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>NH25</span>]   <b class='BibAuthor'>Neunhöffer, M. and Horn, M.</b>,
     <i class='BibTitle'>IO, Bindings for low level C library I/O routines,
             Version 4.9.2</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/io">https://gap-packages.github.io/io</a></span>.
    </p>
    

bibtex: |
    @misc{ IO,
      author =           {Neunh{\"o}ffer, M. and Horn, M.},
      title =            {{IO}, {Bindings for low level C library I/O routines},
                          {V}ersion 4.9.2},
      month =            {Jun},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href              {https://gap-packages.github.io/io}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/io}}},
      keywords =         {input;   output;   I/O;  C\texttt{\symbol{45}}library;
                          network;  http;  object  serialisation;  unpredictable
                          random  numbers;  TCP/IP; inter process communication;
                          background jobs; parallel skeletons; I/O multiplexing},
      printedkey =       {NH25}
    }

