name: IO
version: 4.8.2
date: 2023-10-16
description: |
    Bindings for low level C library I/O routines

authors:
    - name: Max Neunhöffer
      url: mailto:max@9hoeffer.de

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.11"

www: https://gap-packages.github.io/io
readme: README.md
packageinfo: https://gap-packages.github.io/io/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/io/releases/download/v4.8.2/io-4.8.2.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/io/releases/download/v4.8.2/io-4.8.2.tar.bz2

abstract: |
    The <span class="pkgname">IO</span> package, as its name suggests,    provides bindings for <span class="pkgname">GAP</span> to the lower    levels of Input/Output functionality in the C library.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
